### ISSUE TITLE
Implement server-side authentication

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/front-end-monorepo#1306]
We need to handle auth on the server. Specifically, picking up user project preferences for determining workflow selection etc.

cc #365 #1132 

Time estimate: 6 weeks

**Comment by rogerhutchings** [comment]
Okay, made some progress on this today with @camallen, to the point where I got a cookie passed along with the page request :tada:

## Steps to reproduce

- Spin up a local copy of the Panoptes API, set up a new user, and get a `client_id`.

- Update `config/initializers/session_store.rb b/config/initializers/session_store.rb` with the following:

    ```rb
    Rails.application.config.session_store :cookie_store,key: '_Local_Panoptes_session', domain: '.zooniverse.org'
    ```
  _(This step is optional, but helps you identify the cookie passed along with the request as being from your local copy of Panoptes.)_

- Update the `default` block in `config/cors_config.yml`:

    ```yaml
    default: &default
      headers: :any
      request_methods: [delete, get, post, options, put, head]
      expose: [ETag, X-CSRF-Param, X-CSRF-Token]
      max_age: 300
      allows:
        - {
            origins: !ruby/regexp '/^https?:\/\/(127\.0\.0\.1|localhost|[a-z0-9-]+\.local|10\.[0-9]+\.[0-9]+\.[0-9]+|192\.[0-9]+\.[0-9]+\.[0-9]+|[a-z0-9-]+\.zooniverse\.org|[a-z0-9-]+\.(pfe-)?preview\.zooniverse\.org)(:\d+)?$/',
            resource: "/users*",
            credentials: true,
          }
        - {
            origins: !ruby/regexp '/^https?:\/\/(127\.0\.0\.1|localhost|[a-z0-9-]+\.local|10\.[0-9]+\.[0-9]+\.[0-9]+|192\.[0-9]+\.[0-9]+\.[0-9]+|[a-z0-9-]+\.zooniverse\.org|[a-z0-9-]+\.(pfe-)?preview\.zooniverse\.org)(:\d+)?$/',
            resource: "/oauth/*",
            credentials: true,
          }
        - { origins: "*", resource: "*" }
    ```

- Start your local copy of Panoptes with `docker-compose up` (you will need to change the `docker-compose.yml` to change the host port)

- Start your local copy of `app-project`

- Visit `http://local.zooniverse.org:3000/projects/brooke/i-fancy-cats?panoptes-api-host=http%3A%2F%2Flocal.zooniverse.org%3A3001&panoptes-api-application=<client_id>`, replacing `<client_id>` with the actual client id you got in the first step.

- Log in, and refresh

- You should see the `_Local_Panoptes_session` cookie in dev tools, and in the headers of the `req` object if you log it in `app-project`.

## Notes / thoughts

- Setting environment variables for `PANOPTES_API_HOST` etc doesn't work on the client side - they're correctly set on the server-side, but don't get picked up on the client. To test this, omit the `panoptes-api-host` and `panoptes-api-application` query params, and watch it fail. 
- I haven't tried exchanging the cookie for a bearer token yet on the server side
- We'll need a store to keep the bearer token (in volatile state, we don't want to pass it along with the store snapshot to hydrate the store)
- The panoptes auth client is probably going to spam the bejeezus out of the server logs because it `console.log`s everything it does (because it was never designed to be used on a server)
- @camallen is going to need to do some work on https://github.com/zooniverse/Panoptes/issues/3123 to get this working on production / staging
